### ISSUE TITLE
expected instance of Ed25519KeyHash

### ISSUE THREAD

**Issue by heyonggl** [tango-crypto/cardano-wallet-js#19]
Help . Exception is happen. 

=============
//npm i cardano-wallet-js
//npm i @emurgo/cardano-serialization-lib-nodejs

const { Seed } = require('cardano-wallet-js');
const { NetworkInfo, RewardAddress, EnterpriseAddress, StakeCredential } = require('@emurgo/cardano-serialization-lib-nodejs');

// generate a recovery phrase of 15 words (default)
//let recoveryPhrase = Seed.generateRecoveryPhrase();

let words = Seed.toMnemonicList(recoveryPhrase);
//console.log(words);

// get the signing keys (can be offline)
// root -> account -> private
let rootKey = Seed.deriveRootKey(recoveryPhrase);
console.log('');
console.log('rootKey : ' + rootKey.to_bech32());

let accountKey = Seed.deriveAccountKey(rootKey, 0);
console.log('');
console.log('accountKey : ' + accountKey.to_bech32());

let enterpriseSKey = accountKey.derive(0).derive(0).to_raw_key();
console.log('');
console.log('enterpriseSKey : ' + enterpriseSKey.to_bech32());
let enterpriseVKey = enterpriseSKey.to_public();
console.log('');
console.log(enterpriseVKey.hash());
const enterpriseAddr = EnterpriseAddress.new(
  NetworkInfo.mainnet().network_id(),
  StakeCredential.from_keyhash(enterpriseVKey.hash())  ----> exception 
).to_address().to_bech32();
console.log('');
console.log('enterpriseAddr : ' + enterpriseAddr);

================

/data/m_test_ut/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:196
        throw new Error(`expected instance of ${klass.name}`);
        ^

Error: expected instance of Ed25519KeyHash
    at _assertClass (/data/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:196:15)
    at Function.from_keyhash (/data/node_modules/@emurgo/cardano-serialization-lib-nodejs/cardano_serialization_lib.js:9140:9)
    at Object.<anonymous> (/data/m_test_ut/cardano-wallet.js:39:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

**Comment by heyonggl** [comment]
let enterpriseSKey = accountKey.derive(0).derive(0);  // fix 
console.log('');
console.log('enterpriseSKey : ' + enterpriseSKey.to_raw_key().to_bech32());
let enterpriseVKey = enterpriseSKey.to_public();
let enterpriseAddr = Seed.generateEnterpriseAddress(enterpriseVKey).to_bech32();
console.log('');
console.log('enterpriseAddr : ' + enterpriseAddr);
