### ISSUE TITLE
can't find a way around "wallet.forgetTransaction is not a function"

### ISSUE THREAD

**Issue by 34r7h** [tango-crypto/cardano-wallet-js#8]
```
(node:13701) UnhandledPromiseRejectionWarning: TypeError: wallet.forgetTransaction is not a function         │
│                                                 ││ server >     at Object.cancelpayment (/home/34r7h/cardano-api-server/index.js:194:23)                                 │
│                                                 ││ server >     at processTicksAndRejections (internal/process/task_queues.js:95:5)                                      │
│                                                 ││ server >     at async /home/34r7h/cardano-api-server/index.js:441:25
```
Code (method on api {}bject )
```
async cancelpayment(id, txid) { 
        // BROKEN.. function undefined
        let wallet = await api.getwallet(id).then(x=>x)
        console.log(Object.keys(wallet))
        return wallet.forgetTransaction(txid)
    }
```
Express endpoint
```
app.get('/cancel-payment', async (req, res) => {
    let cancelpayment = await api.cancelpayment(req.query.wallet, req.query.tx ).then(x=>x)
    res.send(JSON.stringify(cancelpayment))
    return cancelpayment
})
```

**Comment by leobel** [comment]
Hi @34r7h the function wasn't implemented, check version 1.2.2 which now include the function
