### ISSUE TITLE
Trouble at end of native token minting

### ISSUE THREAD

**Issue by 34r7h** [tango-crypto/cardano-wallet-js#9]
Please help troubleshoot how i'm creating an invalid tx. 

Following the native token example. Probably has to do with the phrase i'm passing in or maybe i'm messing up some async functions. Not sure where the payeer mnemonic is coming from or if i'm supposed to create new keys like the example does. Full API with examples and code is at shwifty.io. Thanks again

## Error
```
{
   code: 'created_invalid_transaction',
   message: `That's embarrassing. It looks like I've created an invalid 
        transaction that could not be parsed by the node. Here's an error 
        message that may help with debugging: HardForkApplyTxEr...
} 
``` 
## Return from submitTx
```
{"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n at createError (/home/34r7h/cardano-api-server/node_modules/axios/lib/core/createError.js:16:15)\n at settle (/home/34r7h/cardano-api-server/node_modules/axios/lib/core/settle.js:17:12)\n at IncomingMessage.handleStreamEnd (/home/34r7h/cardano-api-server/node_modules/axios/lib/adapters/http.js:260:11)\n at IncomingMessage.emit (events.js:388:22)\n at endReadableNT (internal/streams/readable.js:1336:12)\n at processTicksAndRejections (internal/process/task_queues.js:82:21)","config":{"url":"http://localhost:8090/v2/proxy/transactions","method":"post","data":{"type":"Buffer","data":[131,167,0,129,130,88,32,16,60,224,123,61,142,125,154,159,55,153,177,211,45,36,61,245,138,73,36,166,27,121,35,164,172,80,88,51,170,150,240,1,1,130,130,88,57,0,221,56,218,200,219,233,90,216,2,232,232,42,74,170,68,22,146,9,145,139,10,61,65,45,80,102,249,211,168,137,120,16,237,110,182,226,84,150,144,22,43,109,234,207,42,46,57,248,236,93,249,12,90,121,241,101,26,0,22,10,91,130,88,57,0,252,146,194,14,248,72,195,3,25,228,214,35,13,158,84,185,18,85,217,87,175,156,43,223,223,97,96,232,168,137,120,16,237,110,182,226,84,150,144,22,43,109,234,207,42,46,57,248,236,93,249,12,90,121,241,101,26,52,9,169,92,2,26,0,2,197,233,3,26,92,104,70,192,7,88,32,159,67,241,143,129,232,180,241,149,244,144,69,74,152,118,6,53,247,11,20,197,37,231,36,244,22,49,43,4,210,5,39,8,0,9,161,88,28,130,168,29,90,207,53,120,89,183,165,182,98,95,97,75,142,200,29,48,90,10,247,244,108,109,199,41,49,161,72,120,121,109,98,97,98,114,111,2,162,0,130,130,88,32,145,20,47,114,43,63,87,79,67,200,208,122,169,231,244,138,160,174,232,219,44,149,113,58,167,54,9,33,236,20,125,54,88,64,217,98,48,218,79,2,114,221,118,243,105,223,219,177,124,24,209,214,179,93,237,204,234,46,150,186,149,39,22,136,82,75,209,88,115,7,13,214,235,37,237,251,190,150,113,89,153,105,11,172,228,52,38,136,186,153,51,58,149,141,153,222,96,13,130,88,32,190,210,230,156,159,125,113,143,68,58,79,132,68,21,150,142,18,249,207,196,92,103,107,237,10,106,78,88,240,186,162,37,88,64,164,131,140,130,227,197,83,88,51,216,22,81,19,182,141,154,145,225,158,129,208,120,108,55,193,53,233,252,221,136,199,213,36,90,8,65,186,180,37,91,67,49,212,5,176,79,34,193,219,224,160,16,237,135,104,90,199,31,248,62,142,19,198,13,1,129,130,0,88,28,108,87,29,68,126,219,43,177,53,93,55,99,37,86,254,201,218,234,225,158,86,182,61,209,70,24,118,106,246]},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/octet-stream","User-Agent":"axios/0.21.1","Content-Length":504},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
```
## Mint method
```
async mint(id, addresses, meta, name, maxsupply, phrase) {
        let walletserver = api.connect()
        let keys = api.keys()
        let policyvkey = keys.publicKey
        let policyskey = keys.privateKey
        let policyhash = await api.keyhash(policyvkey).then(x=>x).catch(x=>x)
        let script = api.buildscript(policyhash)
        let policyid = api.getpolicyid(api.scripthash(script))
        let tokendata = {}
        let data = {}
        tokendata[policyid] = meta
        data[0] = tokendata
        let asset = new AssetWallet(policyid, name, maxsupply);
        let tokens = [new TokenWallet(asset, script, [keys])];
        let scripts = tokens.map(t => t.script);
        let minada = Seed.getMinUtxoValueWithAssets([asset]);
        let amounts = [minada];
        let info = await api.networkinfo().then(x=>x)
        let ttl = info.node_tip.absolute_slot_number * 12000;
        let coinselection = await api.walletcoinselection(id, null, amounts, data).then(x=>x).catch(x=>x)
        if (typeof phrase === 'string') phrase = phrase.split(',')

        console.log('phrase', phrase);
        let rootkey = api.deriverootkey(phrase)
        let signingkeys = coinselection.inputs.map(i => {
            let privatekey = api.derivekey(rootkey, i.derivation_path)
            return privatekey;
        });
        tokens.filter(t => t.scriptKeyPairs).forEach(t => signingkeys.push(...t.scriptKeyPairs.map(k => k.privateKey.to_raw_key())));
        let metadata = api.buildtxmeta(data)
        coinselection.outputs = coinselection.outputs.map(output => {
            if (output.address === addresses[0].address) {
                output.assets = tokens.map(t => {
                    let asset = {
                        policy_id: t.asset.policy_id,
                        asset_name: t.asset.asset_name,
                        quantity: t.asset.quantity
                    };
                    return asset;
                });
            }
            return output;
        });
        let currentfee = coinselection.inputs.reduce((acc, c) => c.amount.quantity + acc, 0)
           - coinselection.outputs.reduce((acc, c) => c.amount.quantity + acc, 0)
           - coinselection.change.reduce((acc, c) => c.amount.quantity + acc, 0);
        let change = coinselection.change.reduce((acc, c) => c.amount.quantity + acc, 0);
        let rawtxbody = api.buildtx(coinselection, ttl, metadata, tokens);
        let rawtx = api.sign(rawtxbody, signingkeys, metadata, scripts)
        let fee = api.gettxfee(rawtx)
        coinselection.change[0].amount.quantity = change - (parseInt(fee.to_str()) - currentfee);
        let txbody = api.buildtxmint(coinselection, ttl, tokens, signingkeys, data, cardanoconfig)
        // txbody.set_mint(mint);
        let tx = api.sign(txbody, signingkeys, metadata, scripts)
        let signed = Buffer.from(tx.to_bytes()).toString('hex');
        console.log('signed\n', signed, '\ntx\n', tx);
        let submit = await walletserver.submitTx(signed).then(x=>x).catch(e=>e)
        console.log('submit', submit.response.data);
        return submit.toJSON();
    }
```
## http query

https://shwifty.io/mint?id=b112d4a931cd6c51bc04ec2b54112a220e66406d&addresses=addr_test1qzu06fxmkc5hgjxcucuhlx5rwgnphnf6cj3t4gpukp5dkyag39uppmtwkm39f95szc4km6k09ghrn78vthusckne79js6xn5dj&data={"1":{"id":"love","scope":"cardano","refid":"0x"}}&name=xymbabro&maxsupply=2&phrase=grow,doll,joy,ceiling,cage,once,task,soup,fitness,one,recycle,tower,shrug,dentist,fever

## Outputs
```
ttl: 353720316000                                                                                                                                                                                  
tokens: [{"asset":{"policy_id":"01ea493710b00b546d260c849efd5e77ca09a121d039dd22794bbfe7","asset_name":"xymbabro","quantity":"2"},"script":{"ptr":1179952},"scriptKeyPairs":[{"privateKey":{"ptr"  │
keys: [{"ptr":1182640},{"ptr":1182720}
data: {"0":{"01ea493710b00b546d260c849efd5e77ca09a121d039dd22794bbfe7":{"1":{"id":"love","scope":"cardano","refid":"0x"}}}}                                                                        cardanoconfig: [object Object] // from testnet                                                                                                                                                          
signed: 83a700818258202daadd86fbab34160f1f435c70dbbd9a87e483614362ace8789a642af2aeb91601018282583900dd38dac8dbe95ad802e8e82a4aaa44169209918b0a3d412d5066f9d3a8897810ed6eb6e2549690162b6deacf2a2e39f8ec5 
tx: Transaction { ptr: 1231456 }    
```

**Comment by 34r7h** [comment]
Bit more clues from wallet server but i don't understand
```
network > cardano-wallet_1  | [cardano-wallet.wallet-engine:Error:6626] [2021-06-17 12:46:08.30 UTC] Transaction 48585476 failed: HardForkApplyTxErrFromEra S (S (S (Z (WrapApplyTxErr {unwrapApplyTxErr  │
network > cardano-wallet_1  | [cardano-wallet.api-server:Error:6626] [2021-06-17 12:46:08.30 UTC] [RequestId 499] POST /v2/proxy/transactions 500 Internal Server Error in 0.007624024s
```

**Comment by 34r7h** [comment]
For sure it has to do with the mnemonic phrase. i'm pulling in the wallet server, using the wallet id made there with the mnemonic given at creation.. getting the same error using your wallet id and phrase from your tests

**Comment by 34r7h** [comment]
In good faith, please help

https://explorer.cardano.org/en/transaction.html?id=9c9b352257a7cbf7b0a4ddf6c352a5435c80005216806594914c6aa4bef15ee5

**Comment by 34r7h** [comment]
have you tested the minting example? i'm not sure the coinselect function accepts assets...

**Comment by 34r7h** [comment]
LedgerFailure (UtxowFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash "2e31418d87db56a38834be8bf6f5fe55501cc590cafd98789ab01b7f"

**Comment by leobel** [comment]
Hi @34r7h are you sure your wallet id is the one corresponding to your mnemonic phrase? You can test it hitting this endpoint:
http://{your_host}:{your_port}/v2/wallets with payload
```
{
    "name": "wallet-name",
    "mnemonic_sentence":[...], // your mnemonic phrase
    "passphrase": "wallet-passphrase"
}
```

Make sure it matches the id you are using in your code. Also looking at your code I think you aren't using the latest version 1.2.3 or if you do, there is a couple of issue e.g

```js
coinselection.outputs = coinselection.outputs.map(output => {
      if (output.address === addresses[0].address) {
          output.assets = tokens.map(t => {
              let asset = {
                  policy_id: t.asset.policy_id,
                  asset_name: t.asset.asset_name,
                  quantity: t.asset.quantity
              };
              return asset;
          });
      }
      return output;
});
```
here: `t.asset.asset_name` should be replaced by `Buffer.from(t.asset.asset_name).toString('hex')`.
As of v1.2.2, you don't need to calculate the fee by yourself, you can rely on `Seed.buildTransactionWithToken(...)`  here is an example:

```js
// address to hold the minted tokens. You can use which you want.
let addresses = [(await wallet.getAddresses())[0]];

// blockchain config, this is where you can find protocol params, slotsPerKESPeriod etc.
// This lib comes with  Mainnet, Testnet and LocalCluster config (Config.Mainnet, Config.Testnet and Config.LocalCluster), but you may consider provide your own to make sure they are up to date.
// You can find the latest config files here: https://hydra.iohk.io/build/6498473/download/1/index.html
let config = { ..., "protocolParams": {... "minFeeA": 44, ..., "minFeeB": 155381, ...} }

// policy public/private keypair
let keyPair= Seed.generateKeyPair();
let policyVKey = keyPair.publicKey;
let policySKey = keyPair.privateKey;

// generate single issuer native script
let keyHash = Seed.getKeyHash(policyVKey);
let script = Seed.buildSingleIssuerScript(keyHash);

//generate policy id
let scriptHash = Seed.getScriptHash(script);
let policyId = Seed.getPolicyId(scriptHash);

// metadata
let data: any = {};
let tokenData: any = {}
tokenData[policyId] = {
	Tango: {
		arweaveId: "arweave-id",
		ipfsId: "ipfs-id",
		name: "Tango",
		description: "Tango crypto coin",
		type: "Coin"
	}
};
data[0] = tokenData;

// asset
let asset = new AssetWallet(policyId, "Tango", 1000000);

// token
let tokens = [new TokenWallet(asset, script, [keyPair])];

//scripts
let scripts = tokens.map(t => t.script);

// get min ada for address holding tokens
let minAda = Seed.getMinUtxoValueWithAssets([asset], config);
let amounts = [minAda];

// get ttl info
let info = await walletServer.getNetworkInformation();
let ttl = info.node_tip.absolute_slot_number * 12000;

// get coin selection structure (without the assets)
let coinSelection = await wallet.getCoinSelection(addresses, amounts, data);

// add signing keys
let rootKey = Seed.deriveRootKey(payeer.mnemonic_sentence); 
let signingKeys = coinSelection.inputs.map(i => {
	let privateKey = Seed.deriveKey(rootKey, i.derivation_path).to_raw_key();
	return privateKey;
});

// add policy signing keys
tokens.filter(t => t.scriptKeyPairs).forEach(t => signingKeys.push(...t.scriptKeyPairs.map(k => k.privateKey.to_raw_key())));

let metadata = Seed.buildTransactionMetadata(data);

// the wallet currently doesn't support including tokens not previuosly minted
// so we need to include it manually.
coinSelection.outputs = coinSelection.outputs.map(output => {
	if (output.address === addresses[0].address) {
		output.assets = tokens.map(t => {
			let asset: WalletsAssetsAvailable = {
				 policy_id: t.asset.policy_id,
				 asset_name: Buffer.from(t.asset.asset_name).toString('hex'),
				 quantity: t.asset.quantity
			};
			return asset;
		});
	}
	return output;
});

// we need to sing the tx and calculate the actual fee and the build again 
// since the coin selection doesnt calculate the fee with the asset tokens included
let txBody = Seed.buildTransactionWithToken(coinSelection, ttl, tokens, signingKeys, {data: data, config: config});
let tx = Seed.sign(txBody, signingKeys, metadata, scripts);

// submit the tx	
let signed = Buffer.from(tx.to_bytes()).toString('hex');
let txId = await walletServer.submitTx(signed);
```

**NOTE**: don't forget to pass in the config here: `let minAda = Seed.getMinUtxoValueWithAssets([asset], config);` to make sure it will get the min ADA based on the same network

**Comment by leobel** [comment]
> have you tested the minting example? i'm not sure the coinselect function accepts assets...

As of version 1.2.2 this is the signature of `wallet.getCoinSelection(...)`:
```js
async getCoinSelection(addresses: AddressWallet[], amounts: number[], data?: any, assets: {[key: string]: AssetWallet[]} = {}): Promise<CoinSelectionWallet>
```

So yes, you can pass assets

**Comment by 34r7h** [comment]
This update and advice solved the issue. Thank you very much!
